
python3 script_train_C2SEG.py     --xp_name aug_hsi_final     --subset germany --train_sensors hsi --fusion     --train_city augsburg     --train_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --test_city augsburg     --test_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --max_queries 16384 --query_upsample_factor 4     --query_upsample_fraction 0.0 --query_upsample_prob 0.0     --spectral_aug_prob 0.0     --grad_accum 1 --num_workers 4

python3 script_train_C2SEG.py     --xp_name aug_hsi_final     --subset germany --train_sensors hsi --fusion     --train_city augsburg     --train_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --test_city augsburg     --test_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --max_queries 16384 --query_upsample_factor 4     --query_upsample_fraction 0.3 --query_upsample_prob 0.3     --spectral_aug_prob 0.3     --grad_accum 1 --num_workers 4

python3 script_train_C2SEG.py     --xp_name aug_hsi_final     --subset germany --train_sensors hsi --fusion     --train_city augsburg     --train_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --test_city augsburg     --test_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --max_queries 16384 --query_upsample_factor 4     --query_upsample_fraction 0.3 --query_upsample_prob 0.3     --spectral_aug_prob 0.5     --grad_accum 1 --num_workers 4

python3 script_train_C2SEG.py     --xp_name aug_hsi_final     --subset germany --train_sensors hsi --fusion     --train_city augsburg     --train_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --test_city augsburg     --test_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --max_queries 16384 --query_upsample_factor 4     --query_upsample_fraction 0.5 --query_upsample_prob 0.5     --spectral_aug_prob 0.5     --grad_accum 1 --num_workers 4

CUDA_VISIBLE_DEVICES=0 python3 script_train_C2SEG.py     --xp_name aug_hsi_final     --subset germany --train_sensors hsi --fusion     --train_city augsburg     --train_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --test_city augsburg     --test_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --max_queries 16384 --query_upsample_factor 4     --query_upsample_fraction 0.5 --query_upsample_prob 0.5     --spectral_aug_prob 0.5     --grad_accum 1 --num_workers 4

CUDA_VISIBLE_DEVICES=0 python3 script_train_C2SEG.py     --xp_name aug_hsi_final     --subset germany --train_sensors hsi --fusion     --train_city augsburg     --train_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --test_city augsburg     --test_mat ./data/CrossCity/Germany/augsburg_multimodal.mat     --max_queries 16384 --query_upsample_factor 4     --query_upsample_fraction 0.5 --query_upsample_prob 0.5     --spectral_aug_prob 0.5     --grad_accum 3 --num_workers 4